name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: '0 0 * * *'   # Every day at 00:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ShadmanSShuvo

      - name: Commit generated cards
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          message: "Update profile summary cards"
