name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@1aa64e7dcb157b2131ce596f600e457d3bf8a786
        with:
          USERNAME: ShadmanSShuvo
          UTC_OFFSET: 6
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}
